version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci

  pre_build:
    commands:
      - npm run lint

  build:
    commands:
      - ng build --configuration=production
artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/
